### ISSUE TITLE
'NoneType' object has no attribute 'session'

### ISSUE THREAD

**Issue by webjunkie01** [abourget/pyramid_socketio#11]
Hi,
 I've been trying to setup with pyramid 1.2 and 1.3 but always end up receiving this error:

 self.id = self.io.session.session_id
AttributeError: 'NoneType' object has no attribute 'session'
<SocketIOServer fileno=3 address=0.0.0.0:6543>: Failed to handle request:
  request = GET /socket.io/xhr-multipart/ HTTP/1.1 from ('127.0.0.1', 58473)
  application = <pyramid.router.Router object at 0x1cdded0>

 What's the  recommended version of pyramid to try setting up pyramid_socketio?.

**Comment by webjunkie01** [comment]
Before the above error I get:

self.io = request.environ['socketio']
KeyError: 'socketio'
<SocketIOServer fileno=3 address=0.0.0.0:6543>: Failed to handle request:
  request = GET /socket.io/websocket HTTP/1.1 from ('127.0.0.1', 59725)
  application = <pyramid.router.Router object at 0x2037ed0>

**Comment by abourget** [comment]
Which versions of gevent-socketio are you using ?

Last week, during the PyCon 2012 Sprints, much work has been done on the gevent-socketio library, to bring it up to Socket.IO protocol version 0.7+ (works with 0.9).  I highly suggest you take a look.. and there are some pyramid examples.

The pyramid_socketio is not really required anymore..  We might fix it up a bit to ease the integration.. but really, the integration with now is two lines of code.  I think the only reason for pyramid_socketio to exist in the future will be to pass in configuration parameters.

Take a look at http://gevent-socketio.readthedocs.org/en/latest/index.html

**Comment by webjunkie01** [comment]
Hi Alexandre,

I've been using version gevent-socketio 0.3 on pyramid 1.2 and 1.3. But have been getting the same errors. I kind of got frustrated viewing your video and seeing how everything works so perfectly. 

Thanks for the advice, I'll take a look at it. 

Cheers.

**Comment by abourget** [comment]
Sorry, the videos talk about pyramid_socketio.. which is kind of deprecated.  Use gevent-socketio which embodies all of the functionalities that were added in pyramid_socketio.

**Comment by craigdub** [comment]
same issue @webjunkie01  did you find a fix to this?

**Comment by webjunkie01** [comment]
@craigdub You shoud take a look at gevent-socketio instead. https://github.com/abourget/gevent-socketio
